//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.StudentClasses = new HashSet<StudentClass>();
            this.StudentWaitLists = new HashSet<StudentWaitList>();
        }
    
        public int CID { get; set; }
        public int DID { get; set; }
        public int ClassNum { get; set; }
        public int Semester { get; set; }
        public int Years { get; set; }
        public int CRN { get; set; }
        public int CTID { get; set; }
        public string WeekDays { get; set; }
        public string Times { get; set; }
        public int Capcity { get; set; }
        public int CurrentTotal { get; set; }
    
        public virtual ClassType ClassType { get; set; }
        public virtual Department Department { get; set; }
        public virtual Semester Semester1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClass> StudentClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentWaitList> StudentWaitLists { get; set; }
    }
}
